// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxflykpmbtfppdnajgbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4Zmx5a3BtYnRmcHBkbmFqZ2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzgzNjQsImV4cCI6MjA2MDMxNDM2NH0.l1Edncux2o_UawrOAOvFNhAN6nyfFHSqBvcZTvYJs0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);